"""Utility for reversing redaction placeholders back to original values.

The redaction map is stored on the ``RedactionPipeline`` instance after a call to
``redact``.  ``ReverseRedaction`` consumes that map and provides a simple API to
restore redacted text for system‑related fields that must remain traceable (e.g.
debug logs, internal identifiers).  It deliberately avoids exposing user‑PII –
only placeholders that were generated by the pipeline can be reversed.
"""

from typing import Dict


class ReverseRedaction:
    """Restore placeholders to their original strings using a supplied map."""

    def __init__(self, redaction_map: Dict[str, str]):
        # Defensive copy – callers may reuse the map elsewhere.
        self._map = dict(redaction_map)

    def restore(self, text: str) -> str:
        """Replace any known placeholder with its original value.

        Unknown placeholders are left untouched, ensuring we never unintentionally
        inject data that wasn't originally redacted.
        """
        result = text
        for placeholder, original in self._map.items():
            result = result.replace(placeholder, original)
        return result
