"""Initial schema migration generated by Alembic.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-08-25 00:00:00.000000
"""

# revision identifiers, used by Alembic.
revision = '0001_initial_schema'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('run_type', sa.String(), nullable=False),
    sa.Column('failure_mode_tag', sa.String(), nullable=True),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('fixture_path', sa.String(), nullable=False),
    sa.Column('perturbation_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False, server_default='pending'),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text('now()')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_index('idx_runs_run_id', 'runs', ['run_id'], unique=False)
    op.create_index('idx_runs_agent_name', 'runs', ['agent_name'], unique=False)
    op.create_index('idx_runs_failure_mode_tag', 'runs', ['failure_mode_tag'], unique=False)

    op.create_table('perturbations',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('failure_mode_id', sa.String(), nullable=False),
    sa.Column('perturbation_fn', sa.String(), nullable=False),
    sa.Column('args_applied', sa.JSON(), nullable=False, server_default='{}'),
    sa.Column('applied_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['failure_mode_id'], ['failure_modes.id'])
    )
    op.create_index('idx_perturbations_run_id', 'perturbations', ['run_id'], unique=False)
    op.create_index('idx_perturbations_failure_mode_id', 'perturbations', ['failure_mode_id'], unique=False)

    op.create_table('failure_modes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('perturbation_fn', sa.String(), nullable=False),
    sa.Column('perturbation_args', sa.JSON(), nullable=False, server_default='{}'),
    sa.Column('fixture_path', sa.String(), nullable=False),
    sa.Column('expected_perturbed', sa.JSON(), nullable=False),
    sa.Column('expected_control', sa.JSON(), nullable=False),
    sa.Column('realism_bar', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text('now()')),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text('now()')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('failure_modes')
    op.drop_table('perturbations')
    op.drop_index('idx_runs_failure_mode_tag', table_name='runs')
    op.drop_index('idx_runs_agent_name', table_name='runs')
    op.drop_index('idx_runs_run_id', table_name='runs')
    op.drop_table('runs')
    # ### end Alembic commands ###
